# Site settings
title: Pollution is NOT cool, yo
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: # the subpath of your site, e.g. /blog/
url: "http://xiangyikong.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: xiangyikong

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]